### ISSUE TITLE
How to show time in this format?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dahall/TimeSpan2#1]
Hello:
I want to do some testing with your repo.
I created a WinForms project app with Visual Studio 2022, target .NET 6.0.
I installed NUGET package:
PM> Install-Package TimeSpan2 -Version 2.4.2
I added one TimeSpanPicker control to Form1 in Form Designer.

The following is my C# code:
```cs
namespace TimeSpan2Form
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void Form1_Load(object sender, EventArgs e)
        {
            for (int i = 0; i <= 10; i++)
            {
                await Task.Delay(1000);
                TimeSpan time1 = TimeSpan.FromSeconds(i);
                timeSpanPicker1.Value = time1;
            }
        }
    }
}
```
I can see the output like: 1 second; 2 seconds; 3 seconds; ... 10 seconds.
But how I can show the output like: 00:00:01; 00:00:02; 00:00:03; ... 00:00:10
Let me know how I can do this with C#?
Thanks,

I can

**Comment by zydjohnHotmail** [comment]
Hello:
I found your repo source code contains test code, but I can't compile it, I got error messages like:

Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\net40\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\net45\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\net20\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\netcoreapp3.1\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\obj\Debug\net6.0\ref\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\obj\Debug\net5.0\ref\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\net35\TimeSpan2.Core.dll' could not be found
Error	CS0006	Metadata file 'D:\GitHubRepos\TimeSpan2-master\TimeSpan2.Core\bin\Debug\net45\TimeSpan2.Core.dll' could not be found
Let me know how I can compile and run the source code.

**Comment by dahall** [comment]
I am using VS2022 and just open the solution there. I can then run the test executable in debug mode. Try rebuilding the entire solution and then running the test code.

**Comment by dahall** [comment]
The answer to your formatting question is to use the "c" format string (e.g. `timePicker1.FormatString = "c"`).
